// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'class/shipment_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2856360383739716155),
      name: 'ShipmentItem',
      lastPropertyId: const IdUid(7, 7178172810839329549),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 510791957211809242),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3611335655317486948),
            name: 'caption',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2413317333420811468),
            name: 'trackingId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8590420377106920146),
            name: 'serviceName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8517309743371816679),
            name: 'status',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 422976679122968422),
            name: 'lastUpdateTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 7178172810839329549),
            name: 'visible',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2856360383739716155),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ShipmentItem: EntityDefinition<ShipmentItem>(
        model: _entities[0],
        toOneRelations: (ShipmentItem object) => [],
        toManyRelations: (ShipmentItem object) => {},
        getId: (ShipmentItem object) => object.id,
        setId: (ShipmentItem object, int id) {
          object.id = id;
        },
        objectToFB: (ShipmentItem object, fb.Builder fbb) {
          final captionOffset = fbb.writeString(object.caption);
          final trackingIdOffset = fbb.writeString(object.trackingId);
          final serviceNameOffset = fbb.writeString(object.serviceName);
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, captionOffset);
          fbb.addOffset(2, trackingIdOffset);
          fbb.addOffset(3, serviceNameOffset);
          fbb.addOffset(4, statusOffset);
          fbb.addInt64(5, object.lastUpdateTime);
          fbb.addBool(6, object.visible);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ShipmentItem(
              caption: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              trackingId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              serviceName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..status = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..lastUpdateTime =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..visible =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ShipmentItem] entity fields to define ObjectBox queries.
class ShipmentItem_ {
  /// see [ShipmentItem.id]
  static final id =
      QueryIntegerProperty<ShipmentItem>(_entities[0].properties[0]);

  /// see [ShipmentItem.caption]
  static final caption =
      QueryStringProperty<ShipmentItem>(_entities[0].properties[1]);

  /// see [ShipmentItem.trackingId]
  static final trackingId =
      QueryStringProperty<ShipmentItem>(_entities[0].properties[2]);

  /// see [ShipmentItem.serviceName]
  static final serviceName =
      QueryStringProperty<ShipmentItem>(_entities[0].properties[3]);

  /// see [ShipmentItem.status]
  static final status =
      QueryStringProperty<ShipmentItem>(_entities[0].properties[4]);

  /// see [ShipmentItem.lastUpdateTime]
  static final lastUpdateTime =
      QueryIntegerProperty<ShipmentItem>(_entities[0].properties[5]);

  /// see [ShipmentItem.visible]
  static final visible =
      QueryBooleanProperty<ShipmentItem>(_entities[0].properties[6]);
}
